# Site settings
author: Mike Felix
title: Mike's Coding Blog
header-img: img/home-bg.png
email: mikeyfelix99@gmail.com
copyright_name: Mike Felix
description: > # this means to ignore newlines until "baseurl:"
  Blog for coding course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mikejr99

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
